try {
  throw new Error();
} catch {
  console.log('Error');
}
